import { test, expect } from '@playwright/test';
import { readFile } from 'node:fs/promises';
const user = { userId: 'location-test', name: 'Recorded Inspector', role: 'INSPECTOR', inspectorId: 'REAL-001' };
test('fresh positions per inspection and stable location/time in re-audit, history, map and PDF', async ({ page, context }) => {
  const errors: string[] = []; page.on('pageerror', (error) => errors.push(error.message));
  await context.grantPermissions(['geolocation']);
  await context.setGeolocation({ latitude: 12.9716, longitude: 77.5946, accuracy: 8 });
  await page.route('**/api/auth/login', (route) => route.fulfill({ json: { token: 'test-token', user } }));
  await page.goto('/');
  await expect(page.getByText('Offline scanner ready', { exact: false })).toBeVisible();
  await page.getByPlaceholder('e.g. jdoe_inspector').fill('test');
  await page.locator('input[type="password"]').fill('password');
  await page.getByRole('button', { name: 'Sign In', exact: true }).last().click();
  await expect(page.locator('#tab-scanner')).toBeVisible();
  await expect(page.getByRole('button', { name: /Demo/ })).toHaveCount(0);
  await page.locator('#tab-history').click();
  await expect(page.getByRole('button', { name: /Open audit/ })).toHaveCount(0);
  await expect(page.getByText('Today: 0 Scans')).toBeVisible();
  await page.locator('#tab-heatmap').click();
  await expect(page.getByText('No inspections with device coordinates yet.', { exact: false })).toBeVisible();
  await page.locator('#tab-scanner').click();
  await context.setOffline(true);
  const readReports = () => page.evaluate(async () => {
    const db = await new Promise<IDBDatabase>((resolve) => { const req = indexedDB.open('keyval-store'); req.onsuccess = () => resolve(req.result); });
    const reports = await new Promise<any[]>((resolve) => { const req = db.transaction('keyval').objectStore('keyval').getAll(); req.onsuccess = () => resolve(req.result.filter((value: any) => value?.report_json).map((record: any) => JSON.parse(record.report_json))); });
    db.close(); return reports;
  });
  await page.locator('textarea').fill('Product: First Snack\nNet Wt: 100 g\nMRP Rs. 10 incl. of all taxes');
  await page.getByRole('button', { name: 'Re-audit Extracted Tokens' }).click();
  await expect(page.getByText('12.971600°, 77.594600° (accuracy ±8 m)', { exact: true })).toBeVisible();
  await expect.poll(async () => (await readReports()).length).toBe(1);
  const first = (await readReports())[0];
  expect(first.inspection.inspectorName).toBe('Recorded Inspector');
  await context.setGeolocation({ latitude: 28.6139, longitude: 77.209, accuracy: 12 });
  await page.locator('textarea').fill('Product: First Snack\nNet Wt: 100 g\nMRP Rs. 12 incl. of all taxes');
  await page.getByRole('button', { name: 'Re-audit Extracted Tokens' }).click();
  await expect.poll(async () => (await readReports())[0]?.results.find((r: any) => r.ruleId === 'Rule 6(11)')?.details).toContain('0.12');
  expect((await readReports())[0].timestamp).toBe(first.timestamp);
  expect((await readReports())[0].inspection.location).toEqual(first.inspection.location);
  await page.getByRole('button', { name: 'New Scan', exact: true }).click();
  await page.locator('textarea').fill('Product: Second Snack\nNet Wt: 100 g\nMRP Rs. 10 incl. of all taxes');
  await page.getByRole('button', { name: 'Re-audit Extracted Tokens' }).click();
  await expect(page.getByText('28.613900°, 77.209000° (accuracy ±12 m)', { exact: true })).toBeVisible();
  await expect.poll(async () => (await readReports()).length).toBe(2);
  await page.locator('#tab-heatmap').click(); await expect(page.locator('.leaflet-interactive')).toHaveCount(2);
  await page.locator('#tab-history').click(); await page.getByRole('button', { name: /Open audit .*First Snack/ }).click();
  await expect(page.getByText('12.971600°, 77.594600° (accuracy ±8 m)', { exact: true })).toBeVisible();
  const pending = page.waitForEvent('download'); await page.getByRole('button', { name: /PDF/ }).click();
  const pdf = await readFile((await (await pending).path())!); const text = pdf.toString('latin1');
  expect(text).toContain('12.971600'); expect(text).toContain(first.inspection.id);
  expect(text).not.toContain('Bandra'); expect(text).not.toContain('21-DAY');
  await page.screenshot({ path: 'test-results/real-inspection-mobile.png', fullPage: true });
  expect(errors).toEqual([]);
});
